backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "data"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
